#!/usr/bin/env bash
# ping an IP address pass as an argument and displays USAGE

Adr=$1
fileName=$(basename "$0")
regexPtrn="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

if [ $# -ne 1 ]; then
	echo "Usage: $fileName {IP_ADDRESS}"
	exit 1
fi

if [[ $Adr =~ $regexPtrn ]]; then
	ping -c 5 "$Adr"
else
	echo "{IP_ADDRESS}: Invalid Format"
	echo "IP_ADDRESS example: 8.8.8.8"
fi
