#!/usr/bin/env bash
# This script:
# creates file /var/run/myscript.pid
# displays To infinity and beyond indefinitely
# displays I hate the kill command
# displays Y U no love me?!
# deletes file /var/run/myscript.pid

trigger_sig_quit_term() {
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit
}

trigger_sigint() {
	echo "Y U no love me?!"
	exit 0
}

trap "trigger_sig_quit_term" SIGTERM SIGQUIT
trap "trigger_sigint" SIGINT

echo "$$" > /var/run/myscrippt.pid

while "true"; do
	echo "To infinity and beyond"
	sleep 2
done
