#!/usr/bin/env bash
# This script is displaying "Best School" 8 times, bad/good luck ea once

i=0
while [ $i != 10 ]; do
	
	if [ $i == 3 ]; then
		echo "bad luck"
	elif [ $i == 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi

	((i++))
done
