#!/usr/bin/env bash
# ubuntu server config
# localhost -> 127.0.0.2 | facebook.com -> 8.8.8.8

localhost="127.0.0.2 localhost"
facebook="8.8.8.8 facebook.com"

cp /etc/hosts ~/hosts.new
sed -i "s/^.* localhost$/$localhost/g" ~/hosts.new
sed -i "s/^.* facebook.com$/$facebook/g" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
