#!/usr/bin/env bash
# ubuntu server config
# localhost -> 127.0.0.2 | facebook.com -> 8.8.8.8

localhost="127.0.0.2 localhost"
facebook="8.8.8.8 facebook.com"

cp /etc/hosts ~/hosts.new
echo "$localhost" > ~/hosts.new
echo "$facebook" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
